### ISSUE TITLE
möglichkeit einen sos call selber zu beenden

### ISSUE THREAD

**Issue by guru-berlin** [sea-watch/sea-watch-app#16]
wenn möglich auf dem chat einen button positionieren, wo der sos einbringer jeder zeit den fall selber schließen kann

danach eine abfrage

grund:
- wurde gerettet
- bin sicher an lande gekommen
- habe das problem selber gelöst
- habe ausversehen ein SOS geschickt

**Comment by niczem** [comment]
Ich hab das jetzt so gelöst, dass in das feld 'additional_information' ein (Beispiel "closed_by_client because of REASON"). Wäre es hier eventuell Sinnvoll noch eine Nachricht in den Chat zu Pushen?
Ich halte es eventuell für Sinnvoll, dass nur eingeloggte Nutzer Fälle schließen können.
