### ISSUE TITLE
Wo bin ich ? Grenzlinie

### ISSUE THREAD

**Issue by guru-berlin** [sea-watch/sea-watch-app#17]
würde eine glenzlie einführen, die wir erstmal selber einzeichnen (georafische mitte)
der flüchtling, aber auch der rib fahrer sollte jederzeit wissen
1. auf welcher seite er sich befindet
2. wie weit es zur türkischen bzw. zur griechischen seite ist
3. evtl die entfernung zum festland in km /m 
   ausserdem die eigengeschwindigkeit und die bewegungsrichtung in grad (mittelwert aus den letzten 4 positionsangaben in der koordinaten tabelle)

**Comment by niczem** [comment]
Ich würde vorschlagen statt selbst eingezeichneter Grenzlinien folgende zu Nutzen:
http://www.naturalearthdata.com/downloads/
