### ISSUE TITLE
case information list vs. editable options

### ISSUE THREAD

**Issue by Veeebka** [sea-watch/sea-watch-app#42]
Es ist verwirrend, dass nicht alle Informationen in der Informationsliste in der Casebox über "Bearbeiten" geändert werden können. Für Nutzer*innen bleibt so unklar, wie z.B. ein Picture hinzugefügt werden kann.

**Comment by niczem** [comment]
@JoshuaKrueger Hast du eine Idee, wie wir das lösen können?

**Comment by JoshuaKrueger** [comment]
Wäre ne Idee einfach alle Optionen bearbeitbar sind, also das man quasi auch im Nachhinein ein Bild hinzufügen kann.

**Comment by niczem** [comment]
Wir müssen generell die felder direction, distance, picture (eventuell weitere?) aus der case_db nehmen, da diese felder entweder in case_locations bzw case_messages gespeichert werden.
