### ISSUE TITLE
Add Vehicle

### ISSUE THREAD

**Issue by JoshuaKrueger** [sea-watch/sea-watch-app#45]
Feedback beim erstellen eines Vehicle-Users fehlt noch.

**Comment by niczem** [comment]
Wenn die Seite geladen wird braucht es einen moment bis die Javascript Datei nachgeladen wird, welche das onclick event auf den "Add Vehicle"  Button initialisiert wird. Ist das onclick event nicht initialisiert führt dies dazu, dass das Add Vehicle Form nicht in einem Modal geöffnet wird sondern als einfacher Link geöffnet wird, was dann dazu führt, dass es kein feedback gibt, weil das formular so eigentlich nicht angezeigt werden soll.

Ich blende jetzt alles aus bis jquery geladen wird, so sollte dies nicht mehr möglich sein.
