### ISSUE TITLE
Problematik Terminologie Vehicles/Spotters/? für app_spotter login

### ISSUE THREAD

**Issue by niczem** [sea-watch/sea-watch-app#48]
@JoshuaKrueger 
@Veeebka

**Comment by JoshuaKrueger** [comment]
User without Vehicle / User with Vehicle > (Feld für Vehiclename) / Eventuell als Optionsbox und dann hat man eine Liste von einem Vehicles die man dann auswählen kann oder man hat nen Feld wo man das eintragen kann.
