### ISSUE TITLE
Auth not found

### ISSUE THREAD

**Issue by cyroxx** [sea-watch/sea-watch-app#54]
I followed the installation instructions up to Step 5: DB Migration (including). The app is running at `http://localhost/swa/`.
When clicking the link "Safe Passage Admin", it opens up `http://localhost/swa/admin/public/`, which redirects to `http://localhost/swa/admin/public/auth/login` and ends in a 404 Not Found.

In `admin/public/js/config.js`, I already changed  `urlBase`:
```
swAppConfig.urlBase = '//localhost/swa/admin/public/api/';
```

However, this did not work either. Could you help me to get this working?

**Comment by koop-bremen** [comment]
Just set the root directory for the webserver to admin/public. 

This is required for laravel projects:
https://laravel.com/docs/5.3#configuration

That should fix it.

**Comment by niczem** [comment]
@cyroxx did this help?

**Comment by cyroxx** [comment]
@niczem No, it didn't.

### VirtualHost config
I changed my Apache config to the following:
```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/sea-watch-app/admin/public

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```
Now, the application is available through `http://localhost`, but still I get immediately redirected to `http://localhost/auth/login` which results in `404 Not Found`.

### Routes

`/` (root) maps to `HomeController@index`.

For 5641348a0351697eb6d93a8a95bf01a9be18404b, `php artisan route:list | grep auth/` gives:

```
|        | GET|HEAD                       | auth/login/{one?}/{two?}/{three?}/{four?}/{five?}     |                             | App\Http\Controllers\Auth\AuthController@getLogin          | guest           |
|        | POST                           | auth/login/{one?}/{two?}/{three?}/{four?}/{five?}     |                             | App\Http\Controllers\Auth\AuthController@postLogin         | guest           |
|        | GET|HEAD                       | auth/logout/{one?}/{two?}/{three?}/{four?}/{five?}    |                             | App\Http\Controllers\Auth\AuthController@getLogout         |                 |
|        | GET|HEAD                       | auth/register/{one?}/{two?}/{three?}/{four?}/{five?}  |                             | App\Http\Controllers\Auth\AuthController@getRegister       | guest           |
|        | POST                           | auth/register/{one?}/{two?}/{three?}/{four?}/{five?}  |                             | App\Http\Controllers\Auth\AuthController@postRegister      | guest           |
|        | GET|HEAD|POST|PUT|PATCH|DELETE | auth/{_missing}                                       |                             | App\Http\Controllers\Auth\AuthController@missingMethod     | guest           |
```
### mod_rewrite
`mod_rewrite` is enabled as well:
```
$ a2query -m rewrite
rewrite (enabled by site administrator)
```

**Comment by niczem** [comment]
I get the same..
> Routes
> 
> / (root) maps to HomeController@index.
> 
> For 5641348, php artisan route:list | grep auth/ gives:
> 
> ```
> |        | GET|HEAD                       | auth/login/{one?}/{two?}/{three?}/{four?}/{five?}     |                             | App\Http\Controllers\Auth\AuthController@getLogin          | guest           |
> |        | POST                           | auth/login/{one?}/{two?}/{three?}/{four?}/{five?}     |                             | App\Http\Controllers\Auth\AuthController@postLogin         | guest           |
> |        | GET|HEAD                       | auth/logout/{one?}/{two?}/{three?}/{four?}/{five?}    |                             | App\Http\Controllers\Auth\AuthController@getLogout         |                 |
> |        | GET|HEAD                       | auth/register/{one?}/{two?}/{three?}/{four?}/{five?}  |                             | App\Http\Controllers\Auth\AuthController@getRegister       | guest           |
> |        | POST                           | auth/register/{one?}/{two?}/{three?}/{four?}/{five?}  |                             | App\Http\Controllers\Auth\AuthController@postRegister      | guest           |
> |        | GET|HEAD|POST|PUT|PATCH|DELETE | auth/{_missing}                                       |                             | App\Http\Controllers\Auth\AuthController@missingMethod     | guest           |
> 
> ```

Did you enable AllowOverride for your DocumentRoot? If you don't do that, then .htaccess has no effect on mod_rewrite.

Can you try this:
```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/sea-watch-app/admin/public

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        <Directory /var/www/sea-watch-app/admin/public>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
       </Directory>
</VirtualHost>
```

**Comment by cyroxx** [comment]
I added the `AllowOverride All` part and was able to login to the app now:
```
   <Directory /var/www/sea-watch-app/admin/public>
       AllowOverride All
   </Directory>
```

Should we provide some minimal example (also in terms of [least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege)) for the Apache (and maybe Nginx) site configuration? Unfortunately, the Laravel documentation does not seem to cover this topic.

**Comment by niczem** [comment]
Yeah nice :) I added the apache example config to the readme.md.
