### ISSUE TITLE
Operation area can be saved without title

### ISSUE THREAD

**Issue by cyroxx** [sea-watch/sea-watch-app#56]
I created a new operation area, but did not notice that there was a input text field for the title. I was able to save the operation area anyway. I guess this shouldn't be the case?

Also, I noticed that an operation area cannot be edited. Is there a reason for this or would it be okay to edit an existing operation area?

**Comment by niczem** [comment]
The reason why operation areas can not be edited is that I didn't found a possibility to edit given polygons with open layers. Another possibility would be to let people redraw the polygon or to only let them edit the title.
